### ISSUE TITLE
Services/gRPC/Basic_Template doesn't work without snet-daemon (but it doesn't stop)

### ISSUE THREAD

**Issue by astroseger** [singnet/dnn-model-services#32]
After recent changes basic_Template service doesn't work without daemon.

When I start basic_Templace service without daemon it actually starts, so it is running. But I unable to connect to the service.
It was working before you've made some recent changes (I used it in my front-to-back example, because I preferred to start service and daemon separately).

There are two possibilities :
1. We forbid to start this service without the daemon. So it should fail completely.
2. We fix this issue.

**Comment by arturgontijo** [comment]
I think we can provide both options for users:
1 - Run the service (gRPC server) and daemon together, using some flag (eg: `python run_service.py --daemon`)
2 - Or just the service, without daemon (without flag).

This now makes more sense because of huge logs that comes from daemon (btw I love that!).

**Comment by astroseger** [comment]
@arturgontijo 
What was original intention? Should we search for snetd in PATH or in "./"? Because "./" is not always in PATH.

**Comment by astroseger** [comment]
@arturgontijo 
What was the reason to use popen inside threads???

**Comment by arturgontijo** [comment]
>What was original intention? Should we search for snetd in PATH or in "./"? Because "./" is not always in PATH.
Yeah, our Docker container puts `snetd-linux-amd64` inside `/usr/bin/snetd`.

>What was the reason to use popen inside threads? Could we simply remove threads?
Yes, this was part of previous code that setup and run multiple services.

Final point is that this service is just a test for our integration team.
It's definitely not a DNN model service, so sometime we'll have to remove it from here.
I didn't do that because `platform-pipeline` still uses it.

What I suggest is:
- Update `example-service` with gRPC and start to use it for all tests.
- And/or put `basic-service` inside other repo (maybe together with `example-service` or even in `platform-pipeline`)

**Comment by astroseger** [comment]
Even with multiply services you don't need threads... 

Maybe we could simply replace example service with this Basic_Template? It kind of ok for example service?

By the way I've made a pull request for update Basic_Template. Could you take a look?

**Comment by arturgontijo** [comment]
> Even with multiply services you don't need threads...

Not this case but some services need to share memory (loaded model or something).

>Maybe we could simply replace example service with this Basic_Template? It kind of ok for example service?

I think this will be the best option. But maybe other teammates will think that `basic-service` is too basic to be the `example-service`.

>By the way I've made a pull request for update Basic_Template. Could you take a look?

Thanks for that!

**Comment by astroseger** [comment]
> > Even with multiply services you don't need threads...
> 
> Not this case but some services need to share memory (loaded model or something)
Hmm... It still doesn't make sense to me, because popen is used afterwards... And if popen is not used then it make even less sense because  of Global Interpreter Lock. 

Could you point out the service where shared memory is used?

**Comment by arturgontijo** [comment]
Yeah, the GIL could be a problem.
And we will face the gRPC server side fork() limitation too.

BTW this shared memory service is still just a discussion here.

I think it could be useful in cases like:
- User 1 calls service X at localhost:7000, it starts to process data Y and train a model Y.
- User 2 calls service X at localhost:7001, it starts to process data Z and train a model Z.
- User 3 calls service X at localhost:7002, but User 3 needs to process same data Y and train a model that will be exactly the same model Y from User 1. So it would be nice to get this trained model from a shared memory.

To get this we must be able to spawn the 3 gRPC servers from the same process.
I know that this could be accomplished using storage rules for "most wanted" models.

But like I said, it is still just a discussion about the possibility that some service could need to share memory between different users calls.

**Comment by astroseger** [comment]
>     So it would be nice to get this trained model from a shared memory.

Yes..  So my question is: why this "same" process couldn't be the main process? What's the point to make it in the thread?

Because I see you have "threads" in all services here, and in all services you seems to have the same bug: if something happens in process_th, the main thread will not see it. Something as simple as "not found snetd" (main thread will not see exceptions in the process_th!)

Try to run any service without snetd in PATH and see what will happen.

**Comment by arturgontijo** [comment]
> Yes.. So my question is: why this "same" process couldn't be the main process? What's the point to make it in the thread?

Agree, it should be the main process.
Regarding a possible service that needs shared memory...I think that with multiple gRPC endpoint into same machine (running each one in a thread), all created by the main process, it's good to make something like a queue to use unique resources (eg GPU) instead of blocking all calls when the first one is running.

> Try to run any service without snetd in PATH and see what will happen.

Yeah, this is really a bug. I'll fix them following your solution at PR.
I didn't see that cause I always use container that puts `snetd` into PATH.

**Comment by arturgontijo** [comment]
Fixed by #33.
